#菜单导航
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  友链: /friends
  关于: /about

#logo
logo: /images/curegirl.jpeg

#categories-max
categories_max: 5

#tags-max
tags_max: 10

#favicon
favicon: /images/curegirl.jpeg

#site switch
site_search: true

#rss
rss: /atom.xml

#follow 按顺序展示
follow:
  github: 'https://github.com/Wakie01'
  facebook: 'https://www.facebook.com/wewe.liang.16/'
  # instagram: 'https://www.instagram.com/shi_xiaohu/'
  twitter: 'https://twitter.com/Liangweij1'
  # weixin: 'https://github.com/shixiaohu2206'
  # alipay: 'https://github.com/shixiaohu2206'
  # zhihu: 'https://github.com/shixiaohu2206'
  # QQ: 'https://github.com/shixiaohu2206'
  # weibo: 'https://github.com/shixiaohu2206'
  # qqkongjian: 'https://github.com/shixiaohu2206'
  # google: 'https://github.com/shixiaohu2206'

#search post url
search_url: /search.xml

#ICP 皖ICP备16021483号
site_icp: ''

#分享
share:
  - weibo
  - weixin
  - qqkongjian
  - QQ
  - douban
  - facebook
  - twitter
  - google

#cdn script
cdn_script:
  css: 'https://cdn.bootcss.com/require-css/0.1.10/css.min.js'
  pjax: 'https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js'
  av_min: 'https://cdn.jsdelivr.net/npm/leancloud-storage/dist/av-min.js'
  jquery: 'https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js'
  require: 'https://cdn.bootcss.com/require.js/2.3.6/require.min.js'
  confirm: 'https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.js'
  fancybox: 'https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js'
  chart: 'https://cdn.bootcss.com/Chart.js/2.8.0-rc.1/Chart.bundle.min.js'

#cdn css
cdn_css:
  confirm: 'https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.css'
  fancybox: 'https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css'
  chart: 'https://cdn.bootcss.com/Chart.js/2.8.0-rc.1/Chart.min.css'

#baidu push
baidu_push: true

#reward
reward:
  weixin: 'images/weixin.png'
  zhifubao: 'images/zhifubao.png'

#service worker 配合pjax
service_worker:
  open: false #开启sw


friends:
  - name: Baidu
    time: '2020-06-09'
    url: 'https://www.baidu.com/'
    logo: 'http://www.fxunion.com/d/file/c0dbdce1224c0d669b0881c7bda2a119.png'
    intro: ''
  - name: Google
    time: '2020-06-09'
    url: 'https://www.google.com/'
    logo: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1591723616171&di=79633c9d700d266dbf393086d7d4290e&imgtype=0&src=http%3A%2F%2Fbpic.588ku.com%2Felement_origin_min_pic%2F00%2F89%2F91%2F4456ee878f9811a.jpg'
    intro: ''
  - name: Utone
    time: '2020-07-24'
    url: 'https://blog.utone.xyz/'
    logo: 'https://blog.utone.xyz/images/logo.jpeg'
    intro: ''